# Data Preprocessing Tools

## Importing the libraries

In [1]:
# ================================
# Import Required Libraries
# ================================

# 1) NumPy
# Used for numerical operations and working with arrays
import numpy as np

# 2) Matplotlib
# Used for data visualization (we mainly use pyplot module)
import matplotlib.pyplot as plt

# 3) Pandas
# Used for importing datasets and creating:
#    - Feature matrix (X)
#    - Dependent variable vector (y)
import pandas as pd


## Importing the dataset

In [2]:
# =========================================
# Step 1: Load the Dataset
# =========================================

# Create a variable to store the dataset (DataFrame)
dataset = pd.read_csv('Data.csv')


# =========================================
# Step 2: Create Two Entities
# =========================================

# 1) Matrix of Features (Independent Variables)
#    These are the columns used to predict the dependent variable.
#    Usually, they are all columns except the last one.
x = dataset.iloc[:, :-1].values

# 2) Dependent Variable Vector
#    This is the column we want to predict.
#    Usually, it is the last column in the dataset.
y = dataset.iloc[:, -1].values

In [3]:
print(x)

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 nan]
 ['France' 35.0 58000.0]
 ['Spain' nan 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]


In [4]:
print(y)

['No' 'Yes' 'No' 'No' 'Yes' 'Yes' 'No' 'Yes' 'No' 'Yes']


## Taking care of missing data

In [5]:
# =========================================
# Handling Missing Values
# Using Scikit-Learn Library
# =========================================

# Import SimpleImputer to handle missing values
from sklearn.impute import SimpleImputer

# Create an object from SimpleImputer
# missing_values = np.nan  → defines what is considered as missing
# strategy = 'mean'        → replace missing values with the mean of the column

imputer = SimpleImputer(
    missing_values=np.nan,
    strategy='mean'
)

# =========================================
# Apply Imputer on Specific Columns
# =========================================

# x[:, 1:3]  → select columns index 1 and 2
# (All rows, columns from 1 up to but not including 3)

# Step 1: fit()
# Learn the mean of each selected column (ignoring NaN values)
imputer.fit(x[:, 1:3])

# Step 2: transform()
# Replace the missing values with the learned mean
x[:, 1:3] = imputer.transform(x[:, 1:3])


In [6]:
print(x)

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 63777.77777777778]
 ['France' 35.0 58000.0]
 ['Spain' 38.77777777777778 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]


## Encoding categorical data

### Encoding the Independent Variable

In [7]:
# =========================================
# Encoding Categorical Data (Independent Variable)
# =========================================
# We use two main preprocessing classes:
# 1) ColumnTransformer → to apply a transformation on specific columns only
# 2) OneHotEncoder     → to convert categorical values into numerical vectors
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
import numpy as np


# =========================================
# Create ColumnTransformer Object
# =========================================
# ('encoder', OneHotEncoder(), [0])
# - 'encoder'         → name of the transformation (any name you choose)
# - OneHotEncoder()   → the encoding technique
# - [0]               → column index that contains categorical data

# remainder='passthrough'
# → keep the remaining columns unchanged (numerical columns)
ct = ColumnTransformer(
    transformers=[
        ('encoder', OneHotEncoder(), [0])
    ],
    remainder='passthrough'
)


# =========================================
# Apply Encoding
# =========================================
# fit_transform():
# 1) fit()      → learn the unique categories in column 0
# 2) transform()→ convert them into one-hot encoded vectors
x = np.array(ct.fit_transform(x))


In [8]:
print(x)

[[1.0 0.0 0.0 44.0 72000.0]
 [0.0 0.0 1.0 27.0 48000.0]
 [0.0 1.0 0.0 30.0 54000.0]
 [0.0 0.0 1.0 38.0 61000.0]
 [0.0 1.0 0.0 40.0 63777.77777777778]
 [1.0 0.0 0.0 35.0 58000.0]
 [0.0 0.0 1.0 38.77777777777778 52000.0]
 [1.0 0.0 0.0 48.0 79000.0]
 [0.0 1.0 0.0 50.0 83000.0]
 [1.0 0.0 0.0 37.0 67000.0]]


### Encoding the Dependent Variable

In [9]:
# =========================================
# Encoding the Dependent Variable (y)
# =========================================

# Many machine learning algorithms require the target variable (y) to be numeric.
# If y is categorical (e.g., "Yes"/"No"), we need to convert it into numbers.

from sklearn.preprocessing import LabelEncoder

# Create an object from LabelEncoder
# We don't pass anything inside the parentheses
# because LabelEncoder doesn't need any configuration at creation
le = LabelEncoder()


# Fit the encoder on y and transform y
# - fit(): learns all unique classes in y (e.g., "Yes", "No")
# - transform(): converts each class into a number (e.g., "No" → 0, "Yes" → 1)
# - fit_transform(): does both steps in one line
y = le.fit_transform(y)


In [10]:
print(y)

[0 1 0 0 1 1 0 1 0 1]


## Splitting the dataset into the Training set and Test set

In [11]:
# =========================================
# Splitting the Dataset into Training set and Test set
# =========================================

# Import train_test_split from sklearn
from sklearn.model_selection import train_test_split

# Split the dataset into:
# - x_train → Features used for training the model
# - x_test  → Features used for testing the model
# - y_train → Target values for training
# - y_test  → Target values for testing

# test_size=0.2  → 20% of the data will be used for testing
# random_state=1 → Ensures reproducibility (same split every time)

x_train, x_test, y_train, y_test = train_test_split(
    x, y,
    test_size=0.2,
    random_state=1
)

In [12]:
print(x_train)

[[0.0 0.0 1.0 38.77777777777778 52000.0]
 [0.0 1.0 0.0 40.0 63777.77777777778]
 [1.0 0.0 0.0 44.0 72000.0]
 [0.0 0.0 1.0 38.0 61000.0]
 [0.0 0.0 1.0 27.0 48000.0]
 [1.0 0.0 0.0 48.0 79000.0]
 [0.0 1.0 0.0 50.0 83000.0]
 [1.0 0.0 0.0 35.0 58000.0]]


In [13]:
print(x_test)

[[0.0 1.0 0.0 30.0 54000.0]
 [1.0 0.0 0.0 37.0 67000.0]]


In [14]:
print(y_train)

[0 1 0 0 1 1 0 1]


In [15]:
print(y_test)

[0 1]


## Feature Scaling

In [16]:
# =========================================
# Feature Scaling using StandardScaler
# =========================================

from sklearn.preprocessing import StandardScaler

# Create an instance of StandardScaler
sc = StandardScaler()

# Apply scaling on training set (columns starting from index 3 onward)
x_train[:, 3:] = sc.fit_transform(x_train[:, 3:])

# Apply scaling on test set (using same scaler fitted on training data)
x_test[:, 3:] = sc.transform(x_test[:, 3:])


In [17]:
print(x_train)

[[0.0 0.0 1.0 -0.19159184384578545 -1.0781259408412425]
 [0.0 1.0 0.0 -0.014117293757057777 -0.07013167641635372]
 [1.0 0.0 0.0 0.566708506533324 0.633562432710455]
 [0.0 0.0 1.0 -0.30453019390224867 -0.30786617274297867]
 [0.0 0.0 1.0 -1.9018011447007988 -1.420463615551582]
 [1.0 0.0 0.0 1.1475343068237058 1.232653363453549]
 [0.0 1.0 0.0 1.4379472069688968 1.5749910381638885]
 [1.0 0.0 0.0 -0.7401495441200351 -0.5646194287757332]]


In [18]:
print(x_test)

[[0.0 1.0 0.0 -1.4661817944830124 -0.9069571034860727]
 [1.0 0.0 0.0 -0.44973664397484414 0.2056403393225306]]
